<script src="<?php echo base_url().'assets/webadmin/js/jquery-2.1.4.min.js'?>"></script>
<script src="<?php echo base_url().'assets/webadmin/js/jquery.datatables.min.js'?>"></script>
<script src="<?php echo base_url().'assets/webadmin/js/dataTables.bootstrap.js'?>"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/slimScroll/jquery.slimscroll.min.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/metisMenu/dist/metisMenu.min.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/iCheck/icheck.min.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/sparkline/index.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/moment/moment.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/xeditable/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
<script src="<?php echo base_url();?>assets/webadmin/vendor/select2-3.5.2/select2.min.js"></script>
<!-- App scripts -->
<script src="<?php echo base_url();?>assets/webadmin/scripts/homer.js"></script>
